### ISSUE TITLE
TypeError: Illegal buffer

### ISSUE THREAD

**Issue by JakobHartman** [carldanley/node-pokemon-go-api#17]
app-2 error TypeError: Illegal buffer
app-2     at TypeError (native)
app-2     at Function.module.exports.ByteBuffer.wrap (/servers/poke/node_modules/pokemon-go-api/node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
app-2     at Function.Message.decode (/servers/poke/node_modules/pokemon-go-api/node_modules/protobufjs/dist/protobuf.js:2930:84)
app-2     at /servers/poke/node_modules/pokemon-go-api/src/requests/get-map-data.js:28:10
app-2     at tryCatcher (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/util.js:16:23)
app-2     at Promise._settlePromiseFromHandler (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:504:31)
app-2     at Promise._settlePromise (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:561:18)
app-2     at Promise._settlePromise0 (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:606:10)
app-2     at Promise._settlePromises (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:685:18)
app-2     at Async._drainQueue (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/async.js:138:16)
app-2     at Async._drainQueues (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/async.js:148:10)
app-2     at Immediate.Async.drainQueues [as _onImmediate] (/servers/poke/node_modules/pokemon-go-api/node_modules/bluebird/js/release/async.js:17:14)
app-2     at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by JakobHartman** [comment]
seems every request that has a pokemon in it is throwing this error now

**Comment by rafa0809** [comment]
I get this error when I perform multiple requests

**Comment by JakobHartman** [comment]
Stopped getting the error
